services:
  user-service:
    container_name: user-service
    build: .
    ports:
      - ${EXPOSE_PORT}:${PORT}
    restart: on-failure
    volumes:
      - ./:/app/
    depends_on:
      - echo_mysql
    env_file:
      - .env
    environment:
      - DB_CONNECTION=${DB_USER}:${DB_PASSWORD}@tcp(echo_mysql:${DB_PORT})/${DB_NAME}
      - WAIT_HOSTS=${DB_HOST}:${DB_PORT}
      - WAIT_BEFORE_HOSTS=15
      - WAIT_SLEEP_INTERVAL=3
    networks:
      - user-service-network

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - ${EXPOSE_DB_PORT}:${DB_PORT}
    environment:
      - MYSQL_ROOT_HOST=${DB_HOST}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - database_mysql:/var/lib/mysql
    networks:
      - user-service-network

volumes:
  database_mysql:

networks:
  user-service-network:
    driver: bridge